[server]
headless = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#7151A4"
backgroundColor = "#F6F1FD"
secondaryBackgroundColor = "#EEE7FA"
textColor = "#24163B"
